name: Build_All_Platforms
on:
  workflow_dispatch:
  workflow_call:
env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.QUANTANIUM_READ_PAT }}



    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  build_all_wheels:
    needs: build_sdist
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: AMD64
          # - os: macos-13-xlarge
            # arch: arm64
          - os: macos-14
            arch: arm64

    uses: ./.github/workflows/build_core.yml
    with:
      matrix_os: ${{ matrix.os }}
      matrix_arch: ${{ matrix.arch }}
 
    secrets: inherit
