name: Upload Python Package

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]
    branches:
        - 'main'

jobs:

  get-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} and github.repository == 'qperfect-io/quantanium-python'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

          # Gets the whl directly from the created release
      - uses: robinraju/release-downloader@v1
        with:
          extract: true
          token: ${{ secrets.QUANTANIUMPY_PAT }}
          fileName: 'quantanium_wheels.zip'
          out-file-path: 'release-dists'
          tag: ${{ github.ref_name }}

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    needs: get-release
    if: ${{ github.event.workflow_run.conclusion == 'success' }} and github.repository == 'qperfect-io/quantanium-python'
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: production
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/project/YOURPROJECT
      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
      # ALTERNATIVE: exactly, uncomment the following line instead:
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          # password: ${{ secrets.PYPI_PW }}
