name: Upload Python Package

on:
  workflow_dispatch:

jobs:

  get-release:
    runs-on: ubuntu-latest
    if: github.repository == 'qperfect-io/quantanium-python'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download quantanium_wheels.zip from release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: 'quantanium_wheels.zip'
          out-file-path: 'release-dists'

      - name: Upload ZIP for next jobs
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: release-dists/quantanium_wheels.zip

  repair-windows-wheels:
    needs: get-release
    runs-on: windows-latest
    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-zip
          path: dist/

      - name: Extract wheels
        run: |
          mkdir dist\wheelhouse
          powershell -Command "Expand-Archive -Path 'dist\\quantanium_wheels.zip' -DestinationPath 'dist\\wheelhouse'"

      - name: Install Python + delvewheel
        run: |
          python -m pip install --upgrade pip
          pip install delvewheel

      - name: Repair Windows wheels with delvewheel
        shell: cmd
        run: |
          mkdir dist\repaired
          for %%F in (dist\wheelhouse\*win_amd64.whl) do (
            delvewheel repair %%F --add-path dist\wheelhouse --wheel-dir dist\repaired
          )

      - name: Upload repaired wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-repaired-win
          path: dist/repaired/*.whl

  pypi-publish:
    needs: [get-release, repair-windows-wheels]
    runs-on: ubuntu-latest
    if: github.repository == 'qperfect-io/quantanium-python'
    permissions:
      id-token: write
    environment:
      name: production
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download original ZIP
        uses: actions/download-artifact@v4
        with:
          name: dist-zip
          path: dist/

      - name: Unzip original wheels
        run: |
          mkdir dist/wheelhouse
          unzip dist/quantanium_wheels.zip -d dist/wheelhouse

      - name: Download repaired Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: dist-repaired-win
          path: dist/wheelhouse/

      - name: Publish all wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/wheelhouse
          password: ${{ secrets.PYPI_API_TOKEN }}

