name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
     - 'v*'
  release:
    types:
      - published
  workflow_call:

env:
  FORCE_COLOR: 3

jobs:

  build:
    uses:  ./.github/workflows/build_all_platforms.yml
    # uses:  ./.github/workflows/build_all_platforms.yml
    secrets: inherit

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-ubuntu-latest-x86_64
          path: wheelhouse/.
      - uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-windows-latest-AMD64
          path: wheelhouse/.
      - uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-macos-13-x86_64
          path: wheelhouse/.
      - uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-macos-13-xlarge-arm64
          path: wheelhouse/.
      - uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-macos-14-arm64
          path: wheelhouse/.
      # - uses: actions/download-artifact@v4
      #   with:
      #       name: cibw-wheels-ubuntu-latest
      #       path: wheelhouse/.
      # - uses: actions/download-artifact@v4
      #   with:
      #       name: cibw-wheels-macos-14
      #       path: wheelhouse/.
      # - uses: actions/download-artifact@v4
      #   with:
      #       name: cibw-wheels-windows-latest
      #       path: wheelhouse/.


      - name: Zip whls
        run:  zip -r quantanium_wheels.zip wheelhouse/*

      - uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: quantanium_wheels.zip
            tag: ${{ github.ref_name }}
            overwrite: true
