name: Test on Windows

on:
  workflow_dispatch:


jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install quantanium
      - run: python -c "import quantanium; print('It works!')"
