name: Test on Windows

on:
  workflow_dispatch:


jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - run: choco install vcredist140 -y   
      - run: pip install msvc-runtime
      - run: pip install quantanium
      - run: pip show quantanium
      - run  python -c "import os,importlib.util;
              spec = importlib.util.find_spec('quantanium');
              pkg_dir = os.path.dirname(spec.origin);
              dll_dir = os.path.abspath(os.path.join(pkg_dir, os.pardir, 'quantanium.libs'));
              if not os.path.isdir(dll_dir): raise FileNotFoundError(f'quantanium.libs not found at {dll_dir!r}');
              os.add_dll_directory(dll_dir);
              import quantanium;
              print('It works!')"
      #- run: python -c "import quantanium; print('It works!')"
